{
 "title": "Apama Corrilator Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Slowest Receiver Queue Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sag_apama_correlator_slowest_input_queue_size_total"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_apama_correlator_uptime_seconds"
    }
   ]
  },
  {
   "title": "Events on Input Context Queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sag_apama_correlator_queued_input_public_total"
    }
   ]
  },
  {
   "title": "Input Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_queued_input_total",
     "legendFormat": "Events Queued Input"
    },
    {
     "expr": "irate(sag_apama_correlator_input_total[10m])",
     "legendFormat": "Events Retrived/Sec"
    }
   ]
  },
  {
   "title": "Output Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sag_apama_correlator_output_total[10m])",
     "legendFormat": "Events/S"
    },
    {
     "expr": "sag_apama_correlator_queued_output_total",
     "legendFormat": "Events Queued Send"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_physical_memory_bytes",
     "legendFormat": "Physical Memory"
    },
    {
     "expr": "sag_apama_correlator_virtual_memory_bytes",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "Correlator Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_contexts_total",
     "legendFormat": "Contexts"
    },
    {
     "expr": "sag_apama_correlator_monitor_instances_total",
     "legendFormat": "Monitor Instances"
    },
    {
     "expr": "sag_apama_correlator_listeners_total",
     "legendFormat": "Listeners"
    }
   ]
  },
  { "title": "Other Dashboards", "type": "dashlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 } }
 ]
}