{
 "title": "Apama Delivery's Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Number Late Delivery's",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Num_Missed_Delivery"
    }
   ]
  },
  {
   "title": "Number of Deliverys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Num_Total_Delivery"
    }
   ]
  },
  {
   "title": "On Time Delivery",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " sag_apama_correlator_user_Num_Hit_Delivery"
    }
   ]
  },
  {
   "title": "Delivery Chart",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Number Of Deliveys" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Num_Total_Delivery",
     "legendFormat": "Total Delivery"
    },
    {
     "expr": "sag_apama_correlator_user_Num_Hit_Delivery",
     "legendFormat": "On Time Delivery"
    },
    {
     "expr": "sag_apama_correlator_user_Num_Missed_Delivery",
     "legendFormat": "Late Delivery"
    }
   ]
  },
  {
   "title": "Driver Late Package Graph",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Packages Lost" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Driver_1_Miss",
     "legendFormat": "Phil"
    },
    {
     "expr": "sag_apama_correlator_user_Driver_2_Miss",
     "legendFormat": "John"
    },
    {
     "expr": "sag_apama_correlator_user_Driver_3_Miss",
     "legendFormat": "Mark"
    },
    {
     "expr": "sag_apama_correlator_user_Driver_4_Miss",
     "legendFormat": "Bob"
    }
   ]
  },
  {
   "title": "Route Lates Pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Route_1_Lates",
     "legendFormat": "Route 1"
    },
    {
     "expr": "sag_apama_correlator_user_Route_2_Lates",
     "legendFormat": "Route 2"
    },
    {
     "expr": "sag_apama_correlator_user_Route_3_Lates",
     "legendFormat": "Route 3"
    },
    {
     "expr": "sag_apama_correlator_user_Route_4_Lates",
     "legendFormat": "Route 4"
    },
    {
     "expr": "sag_apama_correlator_user_Route_5_Lates",
     "legendFormat": "Route 5"
    },
    {
     "expr": "sag_apama_correlator_user_Route_6_Lates",
     "legendFormat": "Route 6"
    },
    {
     "expr": "sag_apama_correlator_user_Route_7_Lates",
     "legendFormat": "Route 7"
    },
    {
     "expr": "sag_apama_correlator_user_Route_8_Lates",
     "legendFormat": "Route 8"
    },
    {
     "expr": "sag_apama_correlator_user_Route_9_Lates",
     "legendFormat": "Route 9"
    },
    {
     "expr": "sag_apama_correlator_user_Route_10_Lates",
     "legendFormat": "Route 10"
    }
   ]
  },
  {
   "title": "Late Delivery Percentage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sag_apama_correlator_user_Num_Missed_Delivery / sag_apama_correlator_user_Num_Total_Delivery * 100)"
    }
   ]
  },
  {
   "title": "Driver Late Pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Driver_1_Miss",
     "legendFormat": "Phil"
    },
    {
     "expr": "sag_apama_correlator_user_Driver_2_Miss",
     "legendFormat": "John"
    },
    {
     "expr": "sag_apama_correlator_user_Driver_3_Miss",
     "legendFormat": "Mark"
    },
    {
     "expr": "sag_apama_correlator_user_Driver_4_Miss",
     "legendFormat": "Bob"
    }
   ]
  },
  {
   "title": "On Time vs Late Pie Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_Num_Hit_Delivery",
     "legendFormat": "On Time"
    },
    {
     "expr": "sag_apama_correlator_user_Num_Missed_Delivery",
     "legendFormat": "Late"
    }
   ]
  },
  {
   "title": "On Time Delivery Percentage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sag_apama_correlator_user_Num_Hit_Delivery / sag_apama_correlator_user_Num_Total_Delivery * 100)"
    }
   ]
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 } },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "format": "dthms",
   "valueName": "total",
   "targets": [
    {
     "expr": "sag_apama_correlator_uptime_seconds"
    }
   ]
  }
 ]
}